
export const lstActivites = [
  {
    titre: "Cuisine",
    duree_min: 30,
    duree_max: 60,
    constructif: 9,
    energie_physique: 7,
    energie_mentale: 5,
    defoulement: 0,
    relaxation: 2,
    },
  {
    titre: "Guitare",
    duree_min: 10,
    duree_max: 50,
    constructif: 7,
    energie_physique: 7,
    energie_mentale: 7,
    defoulement: 0,
    relaxation: 4,
    },
  {
    titre: "Tâches extérieures (courses, ",
    duree_min: 30,
    duree_max: 90,
    constructif: 9,
    energie_physique: 7,
    energie_mentale: 6,
    defoulement: 0,
    relaxation: 0,
    },
  {
    titre: "Ranger / tâches ménagères / ranger pc...",
    duree_min: 20,
    duree_max: 60,
    constructif: 9,
    energie_physique: 9,
    energie_mentale: 5,
    defoulement: 0,
    relaxation: 2,
    },
  {
    titre: "Famille (téléphoner, écrire carte, réfléchir cadeau...)",
    duree_min: 20,
    duree_max: 60,
    constructif: 7,
    energie_physique: 2,
    energie_mentale: 7,
    defoulement: 0,
    relaxation: 5,
    },
  {
    titre: "Vider tableau",
    duree_min: 30,
    duree_max: 180,
    constructif: 10,
    energie_physique: 7,
    energie_mentale: 7,
    defoulement: 0,
    relaxation: 0,
    },
  {
    titre: "Film",
    duree_min: 90,
    duree_max: 240,
    constructif: 0,
    energie_physique: 1,
    energie_mentale: 2,
    defoulement: 3,
    relaxation: 8,
    },
  {
    titre: "Écrire (GD, wiki...)",
    duree_min: 45,
    duree_max: 90,
    constructif: 9,
    energie_physique: 4,
    energie_mentale: 9,
    defoulement: 2,
    relaxation: 1,
    },
  {
    titre: "Lecture articles web (liste, puis reddit/quora)",
    duree_min: 20,
    duree_max: 50,
    constructif: 5,
    energie_physique: 2,
    energie_mentale: 5,
    defoulement: 5,
    relaxation: 3,
    },
  {
    titre: "Programmer (visio, destin quelconque...)",
    duree_min: 60,
    duree_max: 180,
    constructif: 8,
    energie_physique: 3,
    energie_mentale: 9,
    defoulement: 0,
    relaxation: 0,
    },
  {
    titre: "Sieste",
    duree_min: 60,
    duree_max: 540,
    constructif: 8,
    energie_physique: 0,
    energie_mentale: 0,
    defoulement: 0,
    relaxation: 9,
    },
  {
    titre: "Jeu vidéo stratégie",
    duree_min: 60,
    duree_max: 180,
    constructif: 1,
    energie_physique: 2,
    energie_mentale: 6,
    defoulement: 7,
    relaxation: 3,
    },
  {
    titre: "Sortie promenade",
    duree_min: 90,
    duree_max: 300,
    constructif: 3,
    energie_physique: 6,
    energie_mentale: 5,
    defoulement: 1,
    relaxation: 6,
    },
  {
    titre: "Jeu vidéo de flingues (nuclear throne...)",
    duree_min: 30,
    duree_max: 180,
    constructif: 0,
    energie_physique: 5,
    energie_mentale: 5,
    defoulement: 10,
    relaxation: 5,
    },
  {
    titre: "Lecture complexe (prog, philo, histoire)",
    duree_min: 45,
    duree_max: 120,
    constructif: 8,
    energie_physique: 1,
    energie_mentale: 10,
    defoulement: 0,
    relaxation: 7,
    },
  {
    titre: "Lecture roman/BD/Roman virtuel",
    duree_min: 30,
    duree_max: 120,
    constructif: 3,
    energie_physique: 1,
    energie_mentale: 6,
    defoulement: 4,
    relaxation: 8,
    },
  {
    titre: "Écouter musique",
    duree_min: 40,
    duree_max: 80,
    constructif: 0,
    energie_physique: 0,
    energie_mentale: 3,
    defoulement: 4,
    relaxation: 9,
    },
  {
    titre: "Pompes",
    duree_min: 5,
    duree_max: 10,
    constructif: 8,
    energie_physique: 9,
    energie_mentale: 5,
    defoulement: 6,
    relaxation: 0,
    },
  {
    titre: "Jeu de rôle (préparer séance, dessiner carte...)",
    duree_min: 50,
    duree_max: 180,
    constructif: 7,
    energie_physique: 5,
    energie_mentale: 9,
    defoulement: 1,
    relaxation: 4,
    },
]